name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git perl curl python3

      - name: Clone Theos
        run: |
          git clone https://mirror.ghproxy.com/https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          cd $HOME/theos
          git clone https://mirror.ghproxy.com/https://github.com/theos/sdks.git sdks

      - name: Build Tweak
        run: |
          make

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: libSandboxExt
          path: .theos/obj/arm64e/SandboxExt.dylib
